### ISSUE TITLE
Shortcut for Commit and Discard maybe?

### ISSUE THREAD

**Issue by rin-yato** [outerbase/libsql-studio#114]
### Issue Description
Currently, navigating and editing table cells using the keyboard is a great feature in the application. However, the process of committing changes requires clicking the Commit button, which disrupts the keyboard-centric workflow. To enhance the user experience and improve efficiency, I propose adding a keyboard shortcut (`Cmd+Enter`) to trigger the Commit popup.

### Proposed Solution
-   **Keyboard Shortcut:** Introduce a new keyboard shortcut (`Cmd+Enter`) that triggers the Commit popup when editing table cells.

**Comment by rin-yato** [comment]
Not sure about others, since I use dataflare, they execute the change one by one. Not in batch like LibSqlStudio

**Comment by invisal** [comment]
@rin-yato  in TablePlus, they will use Ctrl + S / Cmd + S

**Comment by rin-yato** [comment]
> @rin-yato in TablePlus, they will use Ctrl + S / Cmd + S

Sounds good!
